name: C/C++ CI

on: [push]

jobs:
  build-ubuntu: #test build for ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../tarball/build ..
      - name: build
        run: cd build && sudo make && sudo make install
      - name: test
        run: cd tarball/build/bin/ && ./main

  build-macos: #test build for mac-os
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake -D CMAKE_INSTALL_PREFIX=../tarball/build ..
      - name: build
        run: cd build && make && make install
      - name: test
        run: cd tarball/build/bin/ && ./main
      - name: make-installer
        run: tar -zcvf macos-build.tar.gz tarball
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-build
          path: macos-build.tar.gz
